# Generated by Django 4.1.2 on 2022-10-07 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="submit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=255)),
                ("dt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50, null=True)),
                ("category", models.CharField(max_length=200, null=True)),
                ("season", models.CharField(max_length=200, null=True)),
                ("stream_duration", models.CharField(max_length=255)),
                ("episodes", models.CharField(max_length=200, null=True)),
                ("mode_category", models.CharField(max_length=200, null=True)),
                ("streaming_platform", models.CharField(max_length=200, null=True)),
                ("dt", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
